# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=b'New User', max_length=20, verbose_name=b'Name')),
                ('image', models.ImageField(null=b'True', upload_to=b'img/', verbose_name=b'Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'New User', max_length=20, verbose_name=b'Name')),
                ('surname', models.CharField(max_length=30, verbose_name=b'Surname')),
                ('image', models.ImageField(null=b'True', upload_to=b'img/', verbose_name=b'Image')),
                ('credit', models.IntegerField(default=0, verbose_name=b'Credit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User ID')),
            ],
        ),
        migrations.AddField(
            model_name='benefit',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Employe'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='supplier_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Service'),
        ),
    ]
