# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employe_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='company',
        ),
    ]
