# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20161125_2248'),
        ('company', '0005_auto_20161125_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Service')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
