# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20161125_2248'),
        ('company', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='company_service',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Service'),
        ),
        migrations.AddField(
            model_name='company_service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
