# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20161127_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyService',
            new_name='Company_Service',
        ),
    ]
