# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20161127_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_service',
            old_name='Service',
            new_name='service',
        ),
    ]
