# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 22:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20161127_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\d{9,15}$')]),
        ),
    ]
