# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_employe_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='supplier_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
    ]
