# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name=b'Service Name')),
                ('service_info', models.CharField(max_length=50, verbose_name=b'Info')),
                ('service_image', models.ImageField(upload_to=b'img/', verbose_name=b'Service Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default=b'New Service', max_length=50, verbose_name=b'Supplier Name')),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Employe ID')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier', verbose_name=b"Supplier's ID"),
        ),
    ]
