# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20161125_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_credit',
            field=models.IntegerField(default=1, verbose_name=b'Service Credit'),
            preserve_default=False,
        ),
    ]
