# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_service_service_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='max_usage',
            field=models.IntegerField(default=1, verbose_name=b'Maximum Usage'),
            preserve_default=False,
        ),
    ]
